{
 "title": "Avenger microservices",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Avengers getAll count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_io_xstefank_AvengerResource_avenger_getAll_counter_total"
    }
   ]
  },
  {
   "title": "Avenger getAll timer seconds",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_io_xstefank_AvengerResource_avenger_getAll_timer_seconds"
    }
   ]
  },
  {
   "title": "Snap create count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_io_xstefank_SnapResource_snap_create_counter_total"
    }
   ]
  },
  {
   "title": "Snap create timer",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "application_io_xstefank_SnapResource_snap_create_timer_seconds"
    }
   ]
  },
  {
   "title": "Avenger create counter",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_io_xstefank_AvengerResource_avenger_create_counter_total"
    }
   ]
  },
  {
   "title": "Avenger create timer",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_io_xstefank_AvengerResource_avenger_create_timer_seconds"
    }
   ]
  },
  {
   "title": "Generated avengers count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_io_xstefank_AvengerGeneratorResource_avenger_generated_counter_total{}"
    }
   ]
  },
  {
   "title": "Snap list count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_io_xstefank_SnapResource_snap_list_counter_total"
    }
   ]
  },
  {
   "title": "Avenger update count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_io_xstefank_AvengerResource_avenger_update_counter_total"
    }
   ]
  },
  {
   "title": "Avenger update timer",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "application_io_xstefank_AvengerResource_avenger_update_timer_seconds"
    }
   ]
  },
  {
   "title": "Snap failures count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_io_xstefank_service_SnapGenerator_snap_failures_counter_total"
    }
   ]
  },
  {
   "title": "Snap list timer",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_io_xstefank_SnapResource_snap_list_timer_seconds"
    }
   ]
  },
  {
   "title": "Avenger delete count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_io_xstefank_AvengerResource_avenger_delete_counter_total"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_io_xstefank_AvengerResource_avenger_delete_timer_seconds"
    }
   ]
  },
  {
   "title": "Tokens generated count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_io_xstefank_TokenResource_tokens_generated_count_total"
    }
   ]
  },
  {
   "title": "Snap Thanos count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_io_xstefank_service_SnapGenerator_snap_thanos_counter_total"
    }
   ]
  }
 ]
}